### ISSUE TITLE
How to implement an integration task

### ISSUE THREAD

**Issue by ahwillia** [murraylab/PsychRNN#28]
I'm interested in implementing a simple integration task, like the one in [Mante, Sussillo, et al., (2013)](https://www.nature.com/articles/nature12742). I don't need the "context-dependent" part of their task for now, so we can ignore that for simplicity.

The problem is that I don't see an easy way to do a cumulative sum within the `task.trial_function(...)` API. What I need to compute is something like:

```
x_t = np.random.randn()
y_t = y_t_minus_one + x_t
```

The only way I see how to make such a calculation right now is to compute the full input trace and output trace inside `task.generate_trial_params(...)`.

```
params['x'] = np.random.randn(num_timesteps)
params['y'] = np.concatenate([0.0, np.cumsum(params['x'][:-1])])
```

But then `trial_function` is just iterating over these already defined arrays... which seems sub-optimal. 

I think I might be trying to follow the example tasks too closely... Can I just override the `task.generate_trial(...)` function and leave `task.trial_function(...)` undefined? Or would that break something?

**Comment by syncrostone** [comment]
Good question -- yes, everything will work fine if you override the `task.generate_trial(...)` function and leave `task.trial_function(...)` undefined.
