### ISSUE TITLE
Minor plotting issue in Hello World! (Minimal_Example.ipynb)

### ISSUE THREAD

**Issue by morteza** [murraylab/PsychRNN#32]
First, thanks a lot for this awesome effort 🏆 🥇 

I just found a minor typo that prevents [Minimal_Example.ipynb](https://github.com/murraylab/PsychRNN/blob/master/docs/notebooks/Minimal_Example.ipynb) from plotting the model output. Since it's [the first step](https://psychrnn.readthedocs.io/en/latest/notebooks/Minimal_Example.html) on your website to get introduced to the package, it might be of your interest to know.

Running this line in Jupyter or Colab

```python
...
# ---------------------- Plot the results ---------------------------
plt.plot(model_output[0][0,:,:])
```

results in `IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed`, and no plot is shown.

It should be like this:

```python
plt.plot(model_output[0,:,:])  # or simply model_output[0]
```

**Comment by syncrostone** [comment]
Thanks for pointing it out @morteza! I must have messed it up when I separated model_output and model_state in the line before. It should be fixed now.

Unfortunately the colab link in the docs is still to the v1.0.0 version, but the jupyter notebook should work, and the fixed colab is available [here](https://colab.research.google.com/github/murraylab/PsychRNN/blob/master/docs/notebooks/Minimal_Example.ipynb).
